### ISSUE TITLE
YSI\y_inline problem

### ISSUE THREAD

**Issue by qSorin** [pawn-lang/YSI-Includes#452] opened 2020-06-01 12:32 UTC
Hello. I have a problem with YSI_Coding\y_inline on OnPlayerConnect

![image](https://user-images.githubusercontent.com/63189561/83409374-f2eed780-a41c-11ea-93e6-bfb9f9f126fa.png)

![image](https://user-images.githubusercontent.com/63189561/83409396-feda9980-a41c-11ea-8016-50971024108c.png)

Help me. Sorry for my bad english !

**Comment by PatrickGTR** [comment] 2020-06-01 13:22
You don't need to use ``mysql_format`` when you use ``MySQL_TQueryInline`` it supports formatted argument already. do that and let me know if the problem still persist.

**Comment by qSorin** [comment] 2020-06-01 13:24
Please gave me a exemple.

**Comment by PatrickGTR** [comment] 2020-06-01 13:29
```c
MySQL_TQueryInline(MySQL, using inline CheckAccount, "SELECT * FROM users WHERE name='%e'", getName(playerid));
```

**Comment by qSorin** [comment] 2020-06-01 13:41
It's the same problem

![image](https://user-images.githubusercontent.com/63189561/83414740-adcfa300-a426-11ea-8131-c33c69cc15e3.png)

**Comment by Y-Less** [comment] 2020-06-01 13:45
Do you get any warnings when compiling?  Which compiler version?  Which YSI version?

**Comment by qSorin** [comment] 2020-06-01 13:47
I have no error. And I use the latest version of ysi

Compiler output:
![image](https://user-images.githubusercontent.com/63189561/83415310-93e29000-a427-11ea-9030-64e79945bf24.png)

**Comment by qSorin** [comment] 2020-06-01 13:49
and the includes that I have
![image](https://user-images.githubusercontent.com/63189561/83415489-c9877900-a427-11ea-8327-899289c26a11.png)

**Comment by Y-Less** [comment] 2020-06-01 14:02
Have you read the heap allocation documentation carefully?  I see you're using `YES_HEAP_MALLOC`.

**Comment by qSorin** [comment] 2020-06-01 14:04
yes, I use it and if I put NO It's the same problem

**Comment by qSorin** [comment] 2020-06-01 15:07
Please help me!!

**Comment by qSorin** [comment] 2020-06-01 18:00
Help me.!

**Comment by qSorin** [comment] 2020-06-02 11:40
Please help me!!!

**Comment by qSorin** [comment] 2020-06-03 13:49
@Y-Less Help me!

**Comment by Y-Less** [comment] 2020-06-07 23:47
OK, to solve this I'm going to need an MCVE, because I can't reproduce it:

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by omcho420** [comment] 2020-06-13 01:47
You are using the wrong function

Use: https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Visual/y_dialog/y_dialog_impl.inc#L98

Instead of: https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Visual/y_dialog/y_dialog_impl.inc#L123

with inline

**Comment by qSorin** [comment] 2020-06-13 22:40
i use easyDialog

**Comment by qSorin** [comment] 2020-06-13 22:53
and i have a error in mysql.log.

![image](https://user-images.githubusercontent.com/63189561/84580684-be4a2b00-ade1-11ea-88b3-43818c2a6303.png)

![image](https://user-images.githubusercontent.com/63189561/84580692-d02bce00-ade1-11ea-81fb-96543fe88cdb.png)

@omcho420 @Y-Less

**Comment by omcho420** [comment] 2020-06-14 03:32
my bad I thought u were using y_inline with Dialog_Show

Your `MySQL_TQueryInline` is wrong it should be
`MySQL_TQueryInline(SQL, using inline checkPlayerAccount, "SELECT FROM `accounts` WHERE `name` = '%e'", getName(playerid));

More about that stuff here

https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Coding/y_inline/y_inline_extra.inc#L92

**Comment by qSorin** [comment] 2020-06-14 13:32
it's a same problem. I use a lastest mysql version r41-4.

**Comment by nathanramli** [comment] 2020-06-14 13:53
I have experiencing the same problem before, but i couldnt find where the problem is. Still figuring out.

**Comment by Y-Less** [comment] 2020-06-14 13:57
> 
> 
> OK, to solve this I'm going to need an MCVE, because I can't reproduce it:
> 
> https://stackoverflow.com/help/minimal-reproducible-example

I still can't guess your code.

**Comment by Y-Less** [comment] 2020-06-14 13:57
Also, stop using easyDialog.  People have issues with that literally every day and yet no-one ever believes me that maybe there's a connection!

**Comment by nathanramli** [comment] 2020-06-14 15:00
Ok, i have found where my problems is.
![image](https://user-images.githubusercontent.com/17245129/84596780-df665680-ae89-11ea-8fb7-c9b4e04301d9.png)

This is kinda weird,
when i use return inside if statement, the inline query doesnt work and printing "Invalid memory access".
But when i remove those both return, 
![image](https://user-images.githubusercontent.com/17245129/84596888-73d0b900-ae8a-11ea-8c76-1f3fbb2924eb.png)
There is no problem, it works perfectly.

YSI Version 5.x
MySQL R41-4

**Comment by qSorin** [comment] 2020-06-14 16:35
Nope, it's a same problem @nathanramli 

![image](https://user-images.githubusercontent.com/63189561/84598819-17639e80-ae76-11ea-9758-bb173d376123.png)

![image](https://user-images.githubusercontent.com/63189561/84598833-29454180-ae76-11ea-865c-fe3f7ae27349.png)

**Comment by Y-Less** [comment] 2020-06-14 16:49
OK, well clearly I'm talking to myself here, so I'm closing this.  You can re-open it when you bother to do the one simple thing I asked you to do to help me solve your issue.

**Closed as completed by Y-Less** 2020-06-14 16:49 UTC
