### ISSUE TITLE
y_va and formatex

### ISSUE THREAD

**Issue by Awsomedude** [pawn-lang/YSI-Includes#196] opened 2017-08-14 18:09 UTC
Hello,

So I tried using this code by Slice http://forum.sa-mp.com/showpost.php?p=1903772&postcount=29 but when I try to compile the script I get `warning 213: tag mismatch` from this line `va_formatex(gs_Buffer, _, fmat, va_start<3>);` it use to work, but when I recently updated the YSI files it started giving me that warning.

Thanks

**Comment by Y-Less** [comment] 2017-08-15 09:28
Use one or the other - either use Slice's code, which is mostly compatibile with y_va AFAIK, but there's no real need for both.  If you want to keep using his `va_formatex`, don't use y_va (which could be tricky if you use ANY of YSI - it is a core library, so included by almost everything else).  Or get rid of his `va_formatex` and use `va_format`.

**Comment by Y-Less** [comment] 2017-08-15 09:30
Unfortunately I changed the way y_va works very fundamentally recently, so I don't think there's any way to fix that tag mismatch.  But with the new y_va, pretty much all functions can be used as passthrough now - you don't need any assembly functions like that one now.

**Comment by Y-Less** [comment] 2017-08-15 09:35
I've just read the rest, to use y_va with formatex now is just:

```pawn
formatex(string, sizeof (string), fmat, ___); // May need STATIC_ARGS equivalent.
```

For example:

```pawn
SendClientMessageEx(playerid, colour, text[], ...)
{
    new string[144];
    formatex(string, sizeof (string), text, ___(3)); // Skip the first three parameters.
    SendClientMessage(playerid, colour, string);
}
```

The three skipped parameters are `playerid`, `colour`, and `text`, as you don't want them in the format.  No extra code required at all any more.

**Comment by Southclaws** [comment] 2017-09-27 18:10
I'm trying to get this working in SS but it's printing out garbage data.

https://github.com/Southclaws/ScavengeSurvive/blob/redis/gamemodes/sss/utils/logging.pwn#L55

```
[DEFAULT] : ▒8↑<lL▒▒
[DEFAULT] : Ԕ↑\▒L@▒
[DEFAULT] : 67510740
[DEFAULT] : ▒LT▒↑L▒▒▒
[DEFAULT] : Դ▒▒↑▒▒↑▒
[DEFAULT] : 67510740
[DEFAULT] : 67510740
[DEFAULT] : 67510740
[DEFAULT] : 67510740
[DEFAULT] : 67510740
[DEFAULT] : 0.000000
[DEFAULT] : 67510740
[DEFAULT] : 67510740
[DEFAULT] : 67510740
[DEFAULT] : 67510740
[DEFAULT] : ▒↑T▒▒
[DEFAULT] : 67511828
[DEFAULT] : ▒↑▒▒▒
```

And this is the call site:

https://github.com/Southclaws/ScavengeSurvive/blob/redis/gamemodes/sss/core/server/settings.pwn#L128

Update: I've removed Slice's `formatex` completely and just used `format` and that doesn't work either, I get slightly different garbage data:

```
[SETTING] :
[SETTING] :
[SETTING] : 0
[SETTING] :
[SETTING] :
[SETTING] : 0
[SETTING] : 0
[SETTING] : 0
[SETTING] : 0
[SETTING] : 0
[SETTING] : 0.000000
[SETTING] : 0
[SETTING] : 0
[SETTING] : 0
[SETTING] : 0
[SETTING] :
[SETTING] : 0
[SETTING] :
```

**Comment by Misiur** [comment] 2017-09-27 18:38
```pawn
#include <a_samp>
#include <YSI\y_va>

main()
{
	new abc[32] = "WAT";
	Test2(abc);
}

Test2(...)
{
	new string[144];
	va_format(string, sizeof (string), "%s", ___);
	print(string);
}
```

```
[debug] Server crashed while executing test.amx
[debug] AMX backtrace:
[debug] #0 native format () from samp-server.exe
[debug] #1 0000df38 in Test2 (... <1 argument>) at test.pwn:13
[debug] #2 0000de8c in main () at test.pwn:7
[debug] Native backtrace:
[debug] #0 0040333d in ?? () from samp-server.exe
[debug] #1 6499d60a in ?? () from plugins\crashdetect.DLL
[debug] #2 649a4078 in ?? () from plugins\crashdetect.DLL
[debug] #3 6499a767 in ?? () from plugins\crashdetect.DLL
[debug] #4 6499d65a in ?? () from plugins\crashdetect.DLL
[debug] #5 64374629 in ?? () from plugins\streamer.DLL
[debug] #6 0046f679 in ?? () from samp-server.exe
[debug] #7 65646f6d in ?? () from samp-server.exe
[debug] #8 65742f73 in ?? () from samp-server.exe
[debug] #9 612e7473 in ?? () from samp-server.exe
[debug] Registers:
[debug] EAX: 00000000 EBX: 00000001 ECX: 00000000 EDX: 00000000
[debug] ESI: 004f4f80 EDI: 005fc838 EBP: 65742f73 ESP: 00515c08
[debug] EIP: 612e7473 EFLAGS: 00010246
[debug] Stack:
[debug] ESP+00000000: 0000786d 00000000 00000000 00000000
[debug] ESP+00000020: 00000000 00000000 00000000 00000000
[debug] ESP+00000040: 00000000 00000000 00000000 00000000
[debug] ESP+00000060: 00000000 00000000 00000000 00000000
[debug] ESP+00000080: 00000000 00000000 00000000 00000000
[debug] ESP+000000a0: 00000000 00000000 00000000 00000000
[debug] ESP+000000c0: 00000000 00000000 00000000 00000000
[debug] ESP+000000e0: 00000000 00000000 00000000 00000000
[debug] ESP+00000100: 00000000 00000000 00000000 00000000
[debug] ESP+00000120: 00000000 00000009 00000000 00000000
[debug] ESP+00000140: 00000000 00000000 00000000 00000000
[debug] ESP+00000160: 00000601 00000006 00000001 00000001
[debug] ESP+00000180: 00000000 00000000 00516020 00000000
[debug] ESP+000001a0: 00000000 00000000 007066e8 ffffffff
[debug] ESP+000001c0: 00706710 ffffffff 00000000 00000000
[debug] ESP+000001e0: 00000000 00000000 00000000 00000fa0
[debug] ESP+00000200: 00000000 00000fa0 00706788 ffffffff
[debug] ESP+00000220: 007067b0 ffffffff 00000000 00000000
[debug] ESP+00000240: 00000000 00000000 00000000 00000fa0
[debug] ESP+00000260: 00000000 00000fa0 00706828 ffffffff
[debug] ESP+00000280: 00706850 ffffffff 00000000 00000000
[debug] ESP+000002a0: 00000000 00000000 00000000 00000fa0
[debug] ESP+000002c0: 00000000 00000fa0 00706be0 ffffffff
[debug] ESP+000002e0: 00706c08 ffffffff 00000000 00000000
[debug] ESP+00000300: 00000000 00000000 00000000 00000000
[debug] ESP+00000320: 7494355f 00000000 00000000 00000000
[debug] ESP+00000340: 0020006c 00750045 006f0072 00650070
[debug] ESP+00000360: 00720061 00200064 00690054 0065006d
[debug] ESP+00000380: 00000000 00000000 00650043 0074006e
[debug] ESP+000003a0: 00650070 006e0061 00440020 00790061
[debug] ESP+000003c0: 0065006d 00000000 00030000 00050000
[debug] ESP+000003e0: 00000000 00000001 00000000 00000000
[debug] Loaded modules:
[debug] 00400000 - 00519000 samp-server.exe
[debug] 76fc0000 - 77140000 ntdll.dll
[debug] 74930000 - 74a40000 kernel32.dll
[debug] 75490000 - 754d7000 KERNELBASE.dll
[debug] 756a0000 - 762ec000 SHELL32.dll
[debug] 769e0000 - 76a8c000 msvcrt.dll
[debug] 74b50000 - 74ba7000 SHLWAPI.dll
[debug] 76b30000 - 76bc0000 GDI32.dll
[debug] 750e0000 - 751e0000 USER32.dll
[debug] 74a40000 - 74ae1000 ADVAPI32.dll
[debug] 76570000 - 76589000 sechost.dll
[debug] 762f0000 - 763e0000 RPCRT4.dll
[debug] 748d0000 - 74930000 SspiCli.dll
[debug] 748c0000 - 748cc000 CRYPTBASE.dll
[debug] 76610000 - 7661a000 LPK.dll
[debug] 766b0000 - 7674d000 USP10.dll
[debug] 6f870000 - 6f877000 WSOCK32.dll
[debug] 74ea0000 - 74ed5000 WS2_32.dll
[debug] 76990000 - 76996000 NSI.dll
[debug] 6c3d0000 - 6c402000 WINMM.dll
[debug] 74af0000 - 74b50000 IMM32.DLL
[debug] 76450000 - 7651c000 MSCTF.dll
[debug] 64980000 - 649d0000 crashdetect.DLL
[debug] 64910000 - 64979000 MSVCP100.dll
[debug] 643d0000 - 6448f000 MSVCR100.dll
[debug] 64370000 - 643ca000 streamer.DLL
[debug] 64300000 - 6436c000 MSVCP140.dll
[debug] 64ac0000 - 64ad4000 VCRUNTIME140.dll
[debug] 723a0000 - 723a4000 api-ms-win-crt-runtime-l1-1-0.dll
[debug] 64210000 - 642f1000 ucrtbase.DLL
[debug] 6c8b0000 - 6c8b3000 api-ms-win-core-timezone-l1-1-0.dll
[debug] 6c410000 - 6c413000 api-ms-win-core-file-l2-1-0.dll
[debug] 64ab0000 - 64ab3000 api-ms-win-core-localization-l1-2-0.dll
[debug] 73340000 - 73343000 api-ms-win-core-synch-l1-2-0.dll
[debug] 64900000 - 64903000 api-ms-win-core-processthreads-l1-1-1.dll
[debug] 64200000 - 64203000 api-ms-win-core-file-l1-2-0.dll
[debug] 641f0000 - 641f4000 api-ms-win-crt-string-l1-1-0.dll
[debug] 641e0000 - 641e3000 api-ms-win-crt-heap-l1-1-0.dll
[debug] 641d0000 - 641d4000 api-ms-win-crt-stdio-l1-1-0.dll
[debug] 641c0000 - 641c4000 api-ms-win-crt-convert-l1-1-0.dll
[debug] 641b0000 - 641b3000 api-ms-win-crt-locale-l1-1-0.dll
[debug] 641a0000 - 641a5000 api-ms-win-crt-math-l1-1-0.dll
[debug] 64190000 - 64195000 api-ms-win-crt-multibyte-l1-1-0.dll
[debug] 64180000 - 64183000 api-ms-win-crt-time-l1-1-0.dll
[debug] 64170000 - 64173000 api-ms-win-crt-filesystem-l1-1-0.dll
[debug] 64160000 - 64163000 api-ms-win-crt-environment-l1-1-0.dll
[debug] 64150000 - 64153000 api-ms-win-crt-utility-l1-1-0.dll
[debug] 10000000 - 1000f000 sscanf.DLL
[debug] 640f0000 - 64142000 mysql.DLL
[debug] 640d0000 - 640ec000 log-core.dll
[debug] 63fe0000 - 640c1000 libmariadb.dll
[debug] 6c8c0000 - 6c8d0000 NLAapi.dll
[debug] 732f0000 - 73300000 napinsp.dll
[debug] 648e0000 - 648f2000 pnrpnsp.dll
[debug] 6fe00000 - 6fe3c000 mswsock.dll
[debug] 6e220000 - 6e264000 DNSAPI.dll
[debug] 732e0000 - 732e8000 winrnr.dll
[debug] 6e200000 - 6e206000 rasadhlp.dll
[debug] 6fdd0000 - 6fdd5000 wshtcpip.dll
[debug] 6fbd0000 - 6fbec000 IPHLPAPI.DLL
[debug] 6fbc0000 - 6fbc7000 WINNSI.DLL
[debug] 6e1c0000 - 6e1f8000 fwpuclnt.dll
Segmentation fault
```

```pawn
#include <a_samp>
#include <YSI\y_va>

main()
{
	new abc[32] = "WAT";
	Test2(abc);
}

Test2(...)
{
	va_printf("Hello 1 %s", ___);
}
```
```
Hello 1
[debug] Run time error 6: "Invalid instruction"
[debug]  Unknown opcode 0x3b6049c at address 0x0000001C
[debug] AMX backtrace:
[debug] #0 00000000 in main ()
Script[gamemodes/test.amx]: Run time error 6: "Invalid instruction"
Number of vehicle models: 0

```

Shit. Will take a look

**Comment by Southclaws** [comment] 2017-09-27 18:40
Wait, what's `va_format` is that a special y_va function? I thought this now worked with regular format or any function with `...` args.

**Comment by Misiur** [comment] 2017-09-27 18:41
It's just for backwards compat, I just like the old syntax, no worries.

**Comment by Y-Less** [comment] 2017-09-27 18:56
Oh dear...  Why is that broken now?

**Comment by Misiur** [comment] 2017-09-27 18:58
This won't be one of my one-line bugfixes this time. I haven't seen y_va2 code yet, and I took a look... code scanner and @ emit, my favourite things to debug

(but I'll try and see which commit broke it at least)

**Comment by Y-Less** [comment] 2017-09-27 19:10
I just did this:

```pawn
static stock y_va_BlankFormat1(...)
{
	new string[144];
	va_format(string, sizeof (string), "%s", ___);
//	print(string);
}

Test:y_va_BlankFormat1()
{
	new abc[32] = "WAT";
	y_va_BlankFormat1(abc);
}

static stock
	YSI_g_sString[144];

static stock y_va_BlankFormat2(...)
{
	new string[144];
	va_format(YSI_g_sString, sizeof (YSI_g_sString), "%s", ___);
//	print(string);
}

Test:y_va_BlankFormat2()
{
	new abc[32] = "WAT";
	y_va_BlankFormat2(abc);
	ASSERT(!strcmp(YSI_g_sString, "WAT"));
}
```

And got nothing.

**Comment by Southclaws** [comment] 2017-09-27 19:19
Could it be the `___(n)` causing it? All of my failing calls used that...

**Comment by Misiur** [comment] 2017-09-27 19:19
Breaking commit: https://github.com/Misiur/YSI-Includes/commit/898917d749f2fb684397bac5686a9b467c48a56b

I was certain that I used new syntax without problems since then, but maybe just with integers or something, I don't know.

**Comment by Southclaws** [comment] 2017-09-27 19:20
Ah, thanks! I'll try resetting my YSI head to 898917d 's parent temporarily

**Comment by Y-Less** [comment] 2017-09-27 20:45
I do test these commits, honestly!  I mean I have a whole load of y_va tests now, that all seem to still pass for me.

Actually - I just had a hunch...

**Comment by Misiur** [comment] 2017-09-27 20:48
@Southclaws it still errors out even previous to that commit, or you can't test for unrelated commit reasons?

**Comment by Y-Less** [comment] 2017-09-27 20:49
What are your compiler settings?  I think that is probably the cause, and why I'm not reproducing it - incorrectly dealing with different debug levels.

**Comment by Southclaws** [comment] 2017-09-27 20:51
https://github.com/Southclaws/ScavengeSurvive/blob/redis/makefile#L25

Please excuse the horrible attempt at package management which resulted in a string of `-i` 😆

**Comment by Misiur** [comment] 2017-09-27 20:53
I just tested with `-O0`, still crashes

**Comment by Y-Less** [comment] 2017-09-27 20:53
Well I think I just fixed it.

**Comment by Southclaws** [comment] 2017-09-27 20:53
Oh, that's right, I couldn't compile with 59a3ee7 because of `sprintf`... and oh, that's great to hear!

**Comment by Y-Less** [comment] 2017-09-27 20:56
Fixed in 8799ac6d8ff077e41ba16a002156387911dd7122

**Comment by Y-Less** [comment] 2017-09-27 20:57
The fix look confusing because I changed a load of comments to be more correct.  However, all that did was reveal that a single `120` should be `112` (the length of the code).

**Comment by Southclaws** [comment] 2017-09-27 20:57
Great, thanks for the fast fix! I'm testing it now.

**Comment by Misiur** [comment] 2017-09-27 21:05
Works for me! How do you even comprehend that codescan code, I don't know

**Comment by Y-Less** [comment] 2017-09-27 21:09
I comprehend that codescan code because I wrote codescan!  All it is doing is looking for certain sequences of opcodes in the assembly:

```pawn
	CodeScanMatcherInit(csmO0B, &CallbackFunc);
	CodeScanMatcherPattern(csmO0B,
		OP(ZERO_PRI)                    // 4
		OP(PUSH_PRI)                    // 8
	);
```

That just means "look for this":

```pawn
#emit ZERO.pri
#emit PUSH.pri
```

And when you find it, call `CallbackFunc` with the address of the start of the code (plus some more information, but don't worry about that).

**Comment by Southclaws** [comment] 2017-09-27 21:12
Damn it seems to be still happening on my end, checked the code and I have the `112` there in y_va/impl - it might just be me being tired and forgetting something but I'm pretty sure I'm loading the correct library with `-i`... I might give up tonight (again) and come back to it tomorrow and see if I can repro the issue properly!

**Comment by Y-Less** [comment] 2017-09-27 22:52
Hmm.  I've tested with all the combinations of `-d` and `-O` I could.  Didn't try using `-i` at all TBH, just compiling normally, but also can't see why that would make a difference.  Of course, that's always a dangerous belief!

**Comment by Southclaws** [comment] 2017-09-28 07:14
Okay so I *definitely* have the latest YSI and it's being compiled into the code. At least it has stopped outputting garbage data, but it's just formatting zero-values into the resultant string:

```
Initialising Scavenge and Survive build 0
```

It actually prints out `0` but there's a check right before the call that would make that impossible so the actual value of the formatted variable definitely isn't zero.

Code: https://github.com/Southclaws/ScavengeSurvive/blob/redis/gamemodes/sss/utils/logging.pwn#L53-L58

Call site: https://github.com/Southclaws/ScavengeSurvive/blob/redis/gamemodes/ScavengeSurvive.pwn#L688-L693 (with check to ensure the build number isn't lower than 1000)

If it helps, here's the assembly for my failing `log` function

```asm

CODE cb	; 8c218
	proc	; log
	; line 36
	break	; 8c21c
	;$lcl text c
	; line 37
	break	; 8c220
	;$lcl buffer fffffc00
	stack fffffc00
	zero.pri
	addr.alt fffffc00
	fill 400
	; line 38
	break	; 8c240
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	const.pri 4
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	const.pri 4
	push.pri
	;$par
	push.c 24
	call YVA2_DummyPush
	heap 4
	stor.i
	move.pri
	push.pri
	;$par
	load.s.pri c
	push.pri
	;$par
	const.pri 100
	push.pri
	;$par
	addr.pri fffffc00
	push.pri
	;$par
	push.c 10
	sysreq.c 14	; format
	stack 14
	heap fffffffc
	;$exp
	; line 39
	break	; 8c2fc
	addr.pri fffffc00
	push.pri
	;$par
	push.c 4
	sysreq.c 6	; print
	stack 8
	;$exp
	stack 400
	zero.pri
	retn

	proc	; dbg
	; line 3d
	break	; 8c338
	;$lcl text 14
	;$lcl level 10
	;$lcl handler c
	; line 3e
	break	; 8c33c
	;$lcl idx fffffffc
	stack fffffffc
	load.s.pri c
	push.pri
	;$par
	push.c 4
	call _debug_get_handler_index
	stor.s.pri fffffffc
	;$exp
	;$lcl bt fffff98c
	stack fffff990
	zero.pri
	addr.alt fffff98c
	fill 670
	; line 42
	break	; 8c388
	const.pri 19c
	push.pri
	;$par
	addr.pri fffff98c
	push.pri
	;$par
	push.c 8
	sysreq.c 8e	; GetBacktrace
	stack c
	not
	jzer 11b2
	;$exp
	; line 43
	break	; 8c3c8
	const.pri 7a0538
	push.pri
	;$par
	push.c 4
	sysreq.c 6	; print
	stack 8
	;$exp
l.11b2		; 8c3f0
	; line 48
	break	; 8c3f0
	load.s.pri 10
	push.pri
	const.pri 79c134
	push.pri
	load.s.pri fffffffc
	bounds 7f
	shl.c.pri 2
	pop.alt
	add
	push.pri
	load.i
	pop.alt
	add
	const.alt 80
	add
	load.i
	pop.alt
	xchg
	sleq
	jzer 11b3
	;$exp
	; line 4a
	break	; 8c460
	;$lcl buffer fffff58c
	stack fffffc00
	zero.pri
	addr.alt fffff58c
	fill 400
	; line 4b
	break	; 8c480
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	const.pri 4
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	const.pri c
	push.pri
	;$par
	push.c 24
	call YVA2_DummyPush
	heap 4
	stor.i
	move.pri
	push.pri
	;$par
	load.s.pri 14
	push.pri
	;$par
	const.pri 100
	push.pri
	;$par
	addr.pri fffff58c
	push.pri
	;$par
	push.c 10
	sysreq.c 14	; format
	stack 14
	heap fffffffc
	;$exp
	; line 4c
	break	; 8c53c
	addr.pri fffff58c
	push.pri
	;$par
	push.c 4
	sysreq.c 6	; print
	stack 8
	;$exp
	stack 400
l.11b3		; 8c56c
	stack 674
	zero.pri
	retn
```

**Comment by Y-Less** [comment] 2017-09-28 08:21
Err, what?

```asm
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	const.pri 4
	push.pri
	;$par
	zero.pri
	push.pri
	;$par
	const.pri c
	push.pri
	;$par
	push.c 24
	call YVA2_DummyPush
```

That is 9 `push.pri`s, followed by `push.c 24`, meaning the compiler is passing 9 parameters, then telling the function it has 24 bytes of data (6 cells, so 6 parameters).  I am not sure how or why.

Edit: No, I'm an idiot, it's HEX.

**Comment by Southclaws** [comment] 2017-09-28 08:31
Oh, does the call site position matter in relation to YSI? If you check where that `log` is called from, it's called from an `OnGameModeInit` public that's present *before* any includes including YSI. Could there be some setup that gets skipped?

Relevant comment:

https://github.com/Southclaws/ScavengeSurvive/blob/redis/gamemodes/ScavengeSurvive.pwn#L80

**Comment by Y-Less** [comment] 2017-09-28 08:38
1) I realised my last post was wrong - the assembly output is all in hex without any prefixes, so `24` is `0x24` is the correct `36`!  That's not a major compiler bug...

2) Yes that's probably the reason.  `OnGameModeInit` hooks, even y_hooks ones, get called from an ALS hook because nothing has been installed yet.  If you want the best results, probably include `YSI_Core\y_utils` before everything else.  That will set up a lot of the most fundamental parts earlier.

**Comment by Southclaws** [comment] 2017-09-28 08:44
Ah! I've had that code for a while so something must have changed between me last touching SS code (admittedly that was probably almost a year ago!).

I'll play around with include ordering and figure it out. As long as I can guarantee config to load before anything else, it'll work fine. If not, I might have to make some weird callback chain thing to make sure everything happens in sequence...

**Comment by Southclaws** [comment] 2017-09-28 08:54
Works like a dream, thanks! :+1: 

Would this be worth documenting? It's a pretty niche edge case...

**Comment by Y-Less** [comment] 2017-09-28 09:04
Better than documenting it - I think I can fix it!

**Comment by Y-Less** [comment] 2017-09-28 09:05
I'm more surprised you didn't get any console warnings about `Bare ___ usage found`.

**Comment by Y-Less** [comment] 2017-09-29 00:42
Alright - I've changed y_va to use lazy initialisation.  Basically, it doesn't do any setup until the first use of `___`.  If you never use it - brilliant, no setup code!  If you use it very early - also brilliant as it has no dependencies and can be done at any time.

I just need to remember to always set up in `OnJITInit`.

**Comment by Y-Less** [comment] 2017-09-29 00:43
Alright - I've changed y_va to use lazy initialisation.  Basically, it doesn't do any setup until the first use of `___`.  If you never use it - brilliant, no setup code!  If you use it very early - also brilliant as it has no dependencies and can be done at any time.

I just need to remember to always set up in `OnJITInit`.

**Closed as completed by Y-Less** 2017-09-29 00:43 UTC
