### ISSUE TITLE
Is existing iterate

### ISSUE THREAD

**Issue by ghost** [pawn-lang/YSI-Includes#155] opened 2017-01-28 19:49 UTC
Hello, 

Im facing to an issue on my server: indeed i used this for my vehicle. But is it by default on YSI includes or should i create it myself ? And if I use it without creating the iterate variable while it was needed could it lag the server ?

`foreach(new v: Vehicle)`

Thanks

**Comment by Y-Less** [comment] 2017-01-28 21:30
The latest versions have this already, yes.  The old ones didn't because of the issues with multiple scripts, in that you could add a vehicle in a filterscript and `foreach` wouldn't be aware of it.  That was fixed with better `y_remote` integration, which is part of the reason why I stopped supporting the stand-alone version (that, and it was just a pain to constantly update two separate but almost identical files - people complained, but I don't think they realise just how many bugs, regressions, and problems the two caused).

**Closed as completed by Y-Less** 2017-01-28 21:30 UTC

**Comment by ghost** [comment] 2017-01-28 21:46
Do I need to use Iter_Add when creating a vehicle ? If yes, what happen if i do not add any vehicle ? Someone reported me a lag (freezing, like if it is an infinite loop) when using the only cmd that used  "foreach(new v: Vehicle)"

**Comment by Y-Less** [comment] 2017-01-29 00:19
No you don't need `Iter_Add`.  And I can't say why your code is going slowly.  `foreach` is just the loop, and will contribute almost no time to the execution of the command.  Lag and infinite loops are different - one is just a bit slow (which would imply slow code within the loop, but not the fault of the loop itself), the other is a literal stop forever.
