### ISSUE TITLE
y_groups fails for an unknown reason

### ISSUE THREAD

**Issue by George480** [pawn-lang/YSI-Includes#411] opened 2020-02-21 08:55 UTC
I decided to code again and after some testing, I noticed that y_groups does not work. It used to work in old gamemodes I was writing.

```Pawn
#include <a_samp>

#include <YSI_Players\y_groups>
#include <YSI_Data\y_iterate>

main()
{
    new Group:test_group = Group_Create("group");

    printf("Group_IsValid(test_group): %d", Group_IsValid(test_group));
	
    Group_SetPlayer(test_group, 5, true);
    Group_SetPlayer(test_group, 7, true);
    Group_SetPlayer(test_group, 89, true);
    Group_SetPlayer(test_group, 50, true);

    printf("Group_GetCount(test_group): %d", Group_GetCount(test_group));
	
    foreach(new playerid : GroupMember(test_group))
    {
        printf("playerid: %d", playerid);
    }
}
```
YSI version 5.03.0689
Compiler version 3.10.10

`Group_SetPlayer` may fail if player is not online but `_: test_group` is 0 and `Group_Create("group")` returns 0. `foreach` also falls into an infinite-loop:
```Pawn
// Output:
 Group_IsValid(test_group): 0
 Group_GetCount(test_group): 0
 playerid: 0
 playerid: 0
 ...
 playerid: 0
 playerid: 0
```

Iterators work without any problem. I tried loading the sample code without any plugin, the problem persists. 

I do not think something in the code broke as other users would already report it but I am clueless why this happens.

**EDIT:** Reverting back to YSI 5.1 (https://github.com/pawn-lang/YSI-Includes/tree/v5.1) fixes the problem.
```Pawn
// Output:
 Group_IsValid(test_group): 1
 Group_GetCount(test_group): 4
 playerid: 5
 playerid: 7
 playerid: 50
 playerid: 89
```

**Comment by George480** [comment] 2020-02-21 21:07
After using the latest version and replacing sub-modules of 5.1 version one-by-one, the problem is in **YSI_Core/y_core** or **YSI_Core/y_master**.

**Comment by George480** [comment] 2020-02-24 20:05
In order to assist you, I managed to get a debug output that might be useful:
```Pawn
 Run time error 4: "Array index out of bounds"
  Attempted to read/write array element at index 66365624 in array of size 138
 AMX backtrace:
 #0 00011694 in CodeScanRunFastPrescan (&proc=@01037c8c -227548, &nextaddr=@01037c88 -331324, searchFuncAddr=247352) at C:\samp037\pawno\include\YSI_Coding\y_va\..\..\YSI_Core\y_core\..\..\amx\codescan.inc:843
 #1 0001191c in bool:CodeScanRunFast (csState[CodeScanner:164]=@0103a55c, searchFuncAddr=247352) at C:\samp037\pawno\include\YSI_Coding\y_va\..\..\YSI_Core\y_core\..\..\amx\codescan.inc:866
 #2 00040ec4 in public Malloc_OnCodeInit () at C:\samp037\pawno\include\YSI_Visual\y_dialog\..\..\YSI_Coding\y_inline\y_inline_impl2.inc:863
 #3 0003b488 in public Yield_OnCodeInit () at C:\samp037\pawno\include\YSI_Visual\y_dialog\..\..\YSI_Coding\y_inline\..\y_malloc\y_malloc_entry.inc:194
 #4 00023210 in public YHNPS_OnCodeInit () at C:\samp037\pawno\include\YSI_Data\y_foreach\y_foreach_yield.inc:60
 #5 00022960 in public Hooks_OnCodeInit () at C:\samp037\pawno\include\YSI_Data\y_foreach\..\..\YSI_Coding\y_hooks\y_hooks_nps.inc:432
 #6 00020b68 in public CGen_OnCodeInit () at C:\samp037\pawno\include\YSI_Data\y_foreach\..\..\YSI_Coding\y_hooks\y_hooks_impl.inc:1213
 #7 0001bc30 in public VA_OnCodeInit () at C:\samp037\pawno\include\YSI_Data\y_foreach\..\..\YSI_Coding\y_hooks\..\y_cgen\y_cgen.inc:194
 #8 00014230 in public ThirdParty_OnCodeInit () at C:\samp037\pawno\include\YSI_Coding\y_va\y_va_impl.inc:252
 #9 00013ff8 in public AMX_OnCodeInit () at C:\samp037\pawno\include\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_thirdpartyinclude.inc:369
 #10 00003428 in public Debug_OnCodeInit () at C:\samp037\pawno\include\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_amx_impl.inc:206
 #11 00002d7c in public ScriptInit_OnCodeInit () at C:\samp037\pawno\include\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_debug_impl.inc:659
 #12 00001e70 in ScriptInit_CallOnCodeInit (bool:jit=false) at C:\samp037\pawno\include\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_scriptinit_impl.inc:193
 #13 0000218c in public _yGUCommand () <@Z:> at C:\samp037\pawno\include\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_scriptinit_impl.inc:339
```

**Comment by George480** [comment] 2020-02-24 20:31
y_groups breaks after this commit: https://github.com/pawn-lang/YSI-Includes/commit/004ca29acc7e272fc7ab5c9154c56ee99e75df3a#diff-4b1b4ca78538e92836116fbdbb36f9b0

After replacing `cellmin` with `cellmax` in this line: https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Core/y_master/y_master__impl.inc#L306 y_groups works again.

**Comment by Y-Less** [comment] 2020-03-26 17:54
Could you test this again please @George480 ?  I've just pushed a fix for another bug from the same commit so it would be good to know if it fixed this as well.

**Comment by George480** [comment] 2020-03-27 09:12
I was unable to because it gives run time error on startup.

main.pwn
```Pawn
#include <a_samp>
#include <YSI_Players\y_groups>

#include "random_module.pwn"

main() {}
```

random_module.pwn
```Pawn
#include <YSI_Coding\y_hooks>

hook OnGameModeInit()
{
    return Y_HOOKS_CONTINUE_RETURN_1;
}
```

Crashdetect output
```Pawn
 Run time error 5: "Invalid memory access"
 AMX backtrace:
 #0 00014290 in DumpAMX_WriteEncoded (File:file=5134872, data[]=@01796850 "", &offset=@0179684c -127, compact=2, c=120, size=48) at C:\...\pawno\include\YSI_Players\y_groups\..\..\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_dumpamx.inc:186
 #1 00014c2c in bool:DumpAMX_WriteAMXCode (File:file=5134872, data[]=@01796850 "", &offset=@0179684c -127, size=48, compact=2) at C:\...\pawno\include\YSI_Players\y_groups\..\..\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_dumpamx.inc:252
 #2 00014f58 in bool:DumpAMX_Write (filename[]=@00009664 "YSI_CACHE.amx") at C:\...\pawno\include\YSI_Players\y_groups\..\..\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\y_dumpamx.inc:282
 #3 00001184 in ScriptInit_CallOnCodeInit (bool:jit=false) at C:\...\pawno\include\YSI_Players\y_groups\..\..\YSI_Core\y_core\y_scriptinit_impl.inc:259
 #4 00001a10 in public YSI_gGroupData@Dist () <@7:> at C:\...\pawno\include\YSI_Players\y_groups\..\..\YSI_Core\y_core\y_scriptinit_impl.inc:508

```

**Comment by George480** [comment] 2020-03-29 14:01
> Could you test this again please @George480 ? I've just pushed a fix for another bug from the same commit so it would be good to know if it fixed this as well.

To answer your question, yes. With `YSI_NO_MODE_CACHE` defined, y_groups works well so far.

**Comment by Y-Less** [comment] 2020-03-29 14:08
I've tried, and cannot reproduce that error.  What plugins are you using?

**Comment by George480** [comment] 2020-03-29 14:11
I replied to the other issue: https://github.com/pawn-lang/YSI-Includes/issues/418#issuecomment-605637626

Only crashdetect.

**Closed as completed** 2020-03-29 15:35 UTC
